/* Local reference mode is explicit. Free-form AI requires the configured server endpoint. */
(() => {
 const $=s=>document.querySelector(s),panel=$('#assistant-panel'),launch=$('#assistant-launch'),log=$('#assistant-log'),form=$('#assistant-form'),input=$('#assistant-input'),send=$('#assistant-send'),status=$('#assistant-status');
 const configuredEndpoint=JSON.parse($('#assistant-config').textContent).endpoint; let endpoint=''; const availability=configuredEndpoint?fetch(configuredEndpoint,{signal:AbortSignal.timeout(5000)}).then(r=>r.ok?r.json():null).then(data=>{if(data?.enabled)endpoint=configuredEndpoint}).catch(()=>{}):Promise.resolve();
 const history=[];let welcomed=false,pending=false;
 const sources={catalog:{label:'Объекты',url:'#catalog'},conditions:{label:'Условия займа',url:'#conditions'},documents:{label:'Документы',url:'#documents'},risks:{label:'Риски',url:'#risks'},flow:{label:'Схема денег',url:'#money-flow'},contact:{label:'Связаться с Investore',url:'mailto:info@investore.club'}};
 function message(role,text,source){const el=document.createElement('div');el.className=`chat-message ${role}`;el.textContent=text;if(source){const a=document.createElement('a');a.href=source.url;a.textContent=source.label;a.addEventListener('click',()=>{if(a.hash)panel.close()});el.append(document.createElement('br'),a)}log.append(el);log.scrollTop=log.scrollHeight;return el}
 function open(){panel.showModal();document.body.classList.add('locked');if(!welcomed){welcomed=true;message('assistant','Здравствуйте! Я помощник Investore. Помогу разобраться в объектах, условиях займа, документах и рисках. Отвечаю только по Investore. Не присылайте личные или банковские данные.')}input.focus();availability.then(()=>{$('#assistant-mode').textContent=endpoint?'ИИ · по материалам Investore':'Справочный режим · ИИ ещё не подключён'})}
 launch.addEventListener('click',open);$('.assistant-close').addEventListener('click',()=>panel.close());
 panel.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.classList.remove('locked');launch.focus({preventScroll:true})});
 panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)panel.close()}});
 function referenceAnswer(text){const q=text.toLowerCase().replace(/ё/g,'е');
  const project=typeof projects!=='undefined'?projects.find(p=>q.includes(p.name.toLowerCase().replace(/ё/g,'е').replace('пр-т ',''))||q.includes(p.id)||p.id==='kozhevnicheskaya'&&q.includes('кожевн')||p.id==='obuhovskoy'&&q.includes('обухов')||p.id==='kirpichnye'&&q.includes('кирпич')||p.id==='yaroslavskoe'&&q.includes('ярослав')||p.id==='veselaya'&&q.includes('весел')||p.id==='irtyshskiy'&&q.includes('иртыш')):null;
  if(project)return [`${project.name}, ${project.city}. Арендаторы: ${project.tenant}. ${project.business||'Виды бизнеса отдельных арендаторов в кабинете не раскрыты'}. Заёмщик: ${project.borrower}. В просмотренной исторической оферте переменная ставка ${project.rate}%, фиксированная — 0,01%, срок — 36 месяцев. Премия 2% условная, при досрочном погашении. Это не подтверждает текущую доступность инвестиции.`,{label:'Карточка в кабинете',url:project.sourceUrl}];
  if(/привет|здравств|кто ты/.test(q))return ['Я справочный помощник по Investore. Могу рассказать об объектах, займах, ставках, документах и рисках. Настоящий ИИ пока не подключён.',sources.flow];
  if(/миним|сколько.*(нач|влож|инвест)|вход|сумм/.test(q))return ['На главной странице указан вход от 10 000 ₽, в FAQ — минимум 100 000 ₽; на вторичном рынке — от 1 000 ₽. Источники расходятся. Минимум сделки проверяется по действующей оферте. Диапазон калькулятора 10 000–600 000 ₽ — иллюстративная модель, а не подтверждение доступной суммы.',sources.conditions];
  if(/ставк|доход|процент|выгод|прибыл/.test(q))return ['По просмотренным офертам: Обуховской Обороны — 20%, остальные пять объектов — 23% переменной ставки. Фиксированные 0,01% и условная премия 2% показаны отдельно. В модели на 100 000 ₽ при 23% получается 1 916,67 ₽ в месяц до налогов и комиссий. Доход не гарантирован; актуальные условия и график — в договоре.',sources.conditions];
  if(/выход|продать|раньше|досроч/.test(q))return ['Досрочный выход предполагает продажу прав требования другому инвестору на вторичном рынке. Наличие покупателя и срок продажи не гарантированы.',sources.risks];
  if(/риск|гарант|просроч|задерж|безопас|банкрот/.test(q))return ['Инвестиции могут привести к потере капитала. Уход арендатора или задержка заёмщика может повлиять на выплаты. Оператор организует взыскание по договору, но возврат денег и его срок не гарантированы. Условия инкассо-цессии и сроки смотрите в документах.',sources.risks];
  if(/документ|договор|оферт|налог|ндфл|комисс/.test(q))return ['На сайте собраны правила, декларация рисков, форма инвестиционного предложения, тарифы, годовые отчёты и архив. При решении нужно проверить действующие документы конкретного займа. Инвестиционное предложение не подменяет отдельную форму договора. Налоги и комиссии зависят от применимых условий.',sources.documents];
  if(/объект|арендатор|недвижим|каталог/.test(q))return ['В прототипе шесть объектов: Обуховской Обороны, Кирпичные выемки, Кожевническая, Ярославское ш., Весёлая и Иртышский. Напишите название объекта — расскажу о доступных данных.',sources.catalog];
  if(/контакт|телефон|почт|связа|поддерж/.test(q))return ['Контакты Investore: 8 800 2000 448, info@investore.club. Оператор — ООО «ИНВЕСТОРИ», ИНН 7842116506.',sources.contact];
  if(/как.*работ|займ|заем|счет|инвестор|компани|investore|инвестори/.test(q))return ['Investore описывает прямые займы собственникам коммерческой недвижимости. Деньги до выдачи находятся на номинальном счёте; затем заём получает собственник. Арендатор платит ему аренду, а заёмщик отвечает за проценты и возврат инвестору. Оператор организует сделку и взыскание.',sources.flow];
  if(/погод|рецепт|стих|футбол|политик|код|программ|переведи|анекдот/.test(q))return ['Я могу отвечать только на вопросы об Investore: объектах, займах, документах и рисках.',null];
  return ['В справочном режиме я не смог сопоставить вопрос с материалами Investore. Уточните, пожалуйста: речь об объекте, ставке, входной сумме, документах или рисках? Для ответа в произвольной форме требуется подключение ИИ.',null];
 }
 async function ask(text){if(pending||!text.trim())return;text=text.trim().slice(0,1500);message('user',text);history.push({role:'user',content:text});input.value='';
  if(!endpoint){const [reply,source]=referenceAnswer(text);message('assistant',reply,source);history.push({role:'assistant',content:reply});return}
  pending=true;send.disabled=true;status.textContent='Готовлю ответ…';
  try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.slice(-12)}),signal:AbortSignal.timeout(25000)});const data=await response.json();if(!response.ok||typeof data.answer!=='string')throw Error('Unavailable');message('assistant',data.answer);history.push({role:'assistant',content:data.answer});status.textContent=''}catch{message('assistant','Сейчас не удалось получить ответ ИИ. Попробуйте ещё раз или свяжитесь с Investore по info@investore.club.',sources.contact);history.pop();status.textContent='Сервис временно недоступен'}finally{pending=false;send.disabled=false;input.focus()}
 }
 form.addEventListener('submit',e=>{e.preventDefault();ask(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();ask(input.value)}});document.querySelectorAll('[data-chat-question]').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.chatQuestion)));
 $('#assistant-mode').textContent=endpoint?'ИИ · по материалам Investore':'Справочный режим · ИИ ещё не подключён';
 const top=$('#back-to-top');function updateTop(){top.hidden=scrollY<innerHeight*.7}updateTop();addEventListener('scroll',updateTop,{passive:true});
 top.addEventListener('click',()=>{scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});$('.brand').focus({preventScroll:true})});
})();


